In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [6]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [8]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [9]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [10]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [11]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [13]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
# Create a StandardScaler object.
# It standardizes features so they have:
# Mean = 0
# Standard Deviation = 1

scaler = StandardScaler()

# Learn the mean and standard deviation from the training data,
# then scale the training data.
# fit() -> learns scaling parameters.
# transform() -> applies the scaling.
# fit_transform() performs both steps together.

X_train = scaler.fit_transform(X_train)

# Scale the test data using the SAME parameters
# learned from the training data.
# Never use fit() on test data to avoid data leakage.

X_test = scaler.transform(X_test)

In [16]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

## Building the ANN Regression Model

### Create the Model
- A `Sequential` model is created to build the neural network layer by layer.
- The first hidden layer contains **64 neurons** with the **ReLU** activation function.
- `input_shape=(X_train.shape[1],)` specifies the number of input features.
- The second hidden layer contains **32 neurons** with the **ReLU** activation function.
- The output layer contains **1 neuron** because this is a **regression problem**.
- No activation function is used in the output layer, allowing it to predict any continuous value.

### Compile the Model
- The **Adam** optimizer is used to update the model weights during training.
- The loss function is **Mean Absolute Error (MAE)**, which calculates the average absolute difference between actual and predicted values.
- The evaluation metric is also **MAE**, making it easy to monitor the model's performance during training.

### Model Summary
- `model.summary()` displays the architecture of the neural network.
- It shows:
  - Number of layers
  - Output shape of each layer
  - Number of trainable parameters
  - Total parameters in the model

In [18]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

c:\Users\Omkar\Desktop\Python\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [21]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [22]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 100385.0703 - mae: 100385.0703 - val_loss: 98543.5156 - val_mae: 98543.5156
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99714.3594 - mae: 99714.3594 - val_loss: 97172.5234 - val_mae: 97172.5234
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97314.3438 - mae: 97314.3438 - val_loss: 93626.3906 - val_mae: 93626.3906
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92540.8750 - mae: 92540.8750 - val_loss: 87622.7969 - val_mae: 87622.7969
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 85483.0391 - mae: 85483.0391 - val_loss: 79737.7344 - val_mae: 79737.7344
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 76909.3594 - mae: 76909.3594 - val_loss: 71160.6250 - val_mae: 71160.6250
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 68256.3281 - mae: 68256.3281 - val_loss: 63323.9219 - val_mae: 63323.9219
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 60892.2852 - mae: 60892.2852 - val_loss: 57392.1641 - val_mae: 57392.1641
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 55694.5352 - mae: 55694.5352 - val_loss: 53630.7656 - val_mae: 53630.7656
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52620.5703 - mae: 52620.5703 - val_loss: 51653.8164 - val_mae: 51653.8164
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51182.2461 - mae: 51182.2461 - val_loss: 51001.2148 - val_mae: 51001.2148
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50613.7305 - mae: 50613.7305 - val_loss: 50799.5508 - val_mae: 50799.5508
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50405.3594 - mae: 50405.3594 - val_loss: 50709.6094 - val_mae: 50709.6094
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50299.6797 - mae: 50299.6797 - val_loss: 50658.9023 - val_mae: 50658.9023
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50228.4688 - mae: 50228.4688 - val_loss: 50615.9453 - val_mae: 50615.9453
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50170.2344 - mae: 50170.2344 - val_loss: 50575.7070 - val_mae: 50575.7070
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50119.1172 - mae: 50119.1172 - val_loss: 50537.0625 - val_mae: 50537.0625
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50075.5000 - mae: 50075.5000 - val_loss: 50505.9609 - val_mae: 50505.9609
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50037.0859 - mae: 50037.0859 - val_loss: 50482.7617 - val_mae: 50482.7617
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49999.2812 - mae: 49999.2812 - val_loss: 50459.8867 - val_mae: 50459.8867
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49965.9844 - mae: 49965.9844 - val_loss: 50428.6797 - val_mae: 50428.6797
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49932.8750 - mae: 49932.8750 - val_loss: 50419.4492 - val_mae: 50419.4492
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49908.4570 - mae: 49908.4570 - val_loss: 50395.8984 - val_mae: 50395.8984
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49879.5469 - mae: 49879.5469 - val_loss: 50378.3867 - val_mae: 50378.3867
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49852.7617 - mae: 49852.7617 - val_loss: 50358.8125 - val_mae: 50358.8125
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49831.0117 - mae: 49831.0117 - val_loss: 50344.0508 - val_mae: 50344.0508
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49808.8750 - mae: 49808.8750 - val_loss: 50330.9570 - val_mae: 50330.9570
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49786.7461 - mae: 49786.7461 - val_loss: 50321.1289 - val_mae: 50321.1289
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49769.4023 - mae: 49769.4023 - val_loss: 50302.8945 - val_mae: 50302.8945
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49749.2422 - mae: 49749.2422 - val_loss: 50300.6484 - val_mae: 50300.6484
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49732.5703 - mae: 49732.5703 - val_loss: 50289.1602 - val_mae: 50289.1602
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49715.3438 - mae: 49715.3438 - val_loss: 50281.4219 - val_mae: 50281.4219
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49696.9766 - mae: 49696.9766 - val_loss: 50266.9492 - val_mae: 50266.9492
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49684.2070 - mae: 49684.2070 - val_loss: 50270.2422 - val_mae: 50270.2422
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49669.7539 - mae: 49669.7539 - val_loss: 50255.4688 - val_mae: 50255.4688
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49654.8281 - mae: 49654.8281 - val_loss: 50261.6914 - val_mae: 50261.6914
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49642.6328 - mae: 49642.6328 - val_loss: 50251.1250 - val_mae: 50251.1250
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49629.4805 - mae: 49629.4805 - val_loss: 50241.3828 - val_mae: 50241.3828
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49619.1680 - mae: 49619.1680 - val_loss: 50239.8125 - val_mae: 50239.8125
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49608.8555 - mae: 49608.8555 - val_loss: 50243.2695 - val_mae: 50243.2695
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49597.1680 - mae: 49597.1680 - val_loss: 50232.9727 - val_mae: 50232.9727
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49588.8594 - mae: 49588.8594 - val_loss: 50227.2578 - val_mae: 50227.2578
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49579.7930 - mae: 49579.7930 - val_loss: 50233.6406 - val_mae: 50233.6406
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49571.0781 - mae: 49571.0781 - val_loss: 50228.2695 - val_mae: 50228.2695
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49561.3203 - mae: 49561.3203 - val_loss: 50226.1250 - val_mae: 50226.1250
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49551.7617 - mae: 49551.7617 - val_loss: 50215.0039 - val_mae: 50215.0039
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49541.3398 - mae: 49541.3398 - val_loss: 50217.4414 - val_mae: 50217.4414
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49537.4961 - mae: 49537.4961 - val_loss: 50222.6406 - val_mae: 50222.6406
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49528.2109 - mae: 49528.2109 - val_loss: 50223.3242 - val_mae: 50223.3242
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49518.8008 - mae: 49518.8008 - val_loss: 50206.9414 - val_mae: 50206.9414
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49515.3359 - mae: 49515.3359 - val_loss: 50207.1836 - val_mae: 50207.1836
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49504.4023 - mae: 49504.4023 - val_loss: 50204.2188 - val_mae: 50204.2188
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49500.0430 - mae: 49500.0430 - val_loss: 50207.4883 - val_mae: 50207.4883
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49493.6484 - mae: 49493.6484 - val_loss: 50216.0469 - val_mae: 50216.0469
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49485.6992 - mae: 49485.6992 - val_loss: 50234.2109 - val_mae: 50234.2109
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49480.8945 - mae: 49480.8945 - val_loss: 50225.2109 - val_mae: 50225.2109
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49473.1289 - mae: 49473.1289 - val_loss: 50222.1797 - val_mae: 50222.1797
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49466.5781 - mae: 49466.5781 - val_loss: 50205.9766 - val_mae: 50205.9766
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49462.8984 - mae: 49462.8984 - val_loss: 50216.8555 - val_mae: 50216.8555
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49456.3750 - mae: 49456.3750 - val_loss: 50220.0000 - val_mae: 50220.0000
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49453.7617 - mae: 49453.7617 - val_loss: 50214.8281 - val_mae: 50214.8281
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49447.2695 - mae: 49447.2695 - val_loss: 50216.6406 - val_mae: 50216.6406

In [23]:
%load_ext tensorboard

In [25]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 23100), started 0:00:14 ago. (Use '!kill 23100' to kill it.)

## Evaluating the Model

### Evaluate on Test Data
- The trained model is evaluated using the test dataset.
- `model.evaluate()` calculates the **loss** and the evaluation metric on unseen data.
- Here, it returns:
  - `test_loss` → Value of the loss function (**Mean Absolute Error**).
  - `test_mae` → Mean Absolute Error (MAE), which measures the average prediction error.

```python
test_loss, test_mae = model.evaluate(X_test, y_test)
```

### Display the MAE
- Print the Mean Absolute Error on the test data.
- A **lower MAE** indicates better prediction accuracy.

```python
print(f'Test MAE: {test_mae}')
```

### Why Evaluate on Test Data?
- Measures how well the model performs on unseen data.
- Helps determine whether the model generalizes well.
- Used to assess the final performance of the trained model.

In [26]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50204.2188 - mae: 50204.2188
Test MAE : 50204.21875

In [27]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.